server:
  port: 8081

spring:
  main:
    web-application-type: none
  data:
    cassandra:
      session-name: "Data Cluster"
      username: phd
      password: phd
      keyspace-name: phd
      port: 9042
      contact-points: localhost
      local-datacenter: datacenter1
      request:
        timeout: 15s

vvdump:
  named-pipe-path: "/tmp/vvdump"
  sql:
    postgres:
      insert-variable-value-trace-query: "INSERT INTO variable_value_trace VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      insert-fuzzed-process-info-query: "INSERT INTO fuzzed_process_info VALUES (?, ?, ?, ?, ?, ?, ?, current_timestamp)"
      delete-variable-value-traces-query: "DELETE FROM variable_value_trace WHERE pid = ?"
    cassandra:
      trace-table-fields:
        experiments:
          - experiment
        experiment_subjects:
          - experiment
          - subject
        experiment_subject_binaries:
          - experiment
          - subject
          - binary
        experiment_subject_binary_executions:
          - experiment
          - subject
          - binary
          - execution
        subject_files:
          - subject
          - filename
        subject_file_functions:
          - subject
          - filename
          - function_name
        subject_file_function_variables:
          - subject
          - filename
          - function_name
          - variable_type
          - variable_name
          - declared_line
        subject_file_function_variables_by_declaration_order:
          - subject
          - filename
          - function_name
          - declared_line
          - variable_type
          - variable_name
        processes:
          - experiment
          - subject
          - binary
          - execution
          - pid
          - exit_status
          - input_size
        process_variable_value_traces:
          - id
          - experiment
          - subject
          - binary
          - execution
          - pid
          - exit_status
          - input_size
          - filename
          - function_name
          - declared_line
          - variable_type
          - variable_name
          - timestamp
          - modified_line
          - variable_value

logging:
  file:
    name: /tmp/vvdproc.log
  level:
    root: INFO
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
