server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: "none"
    properties:
      jdbc:
        lob:
          non_contextual_creation: "true"
  datasource:
    initialization-mode: "always"
    platform: "postgres"
    url: "jdbc:postgresql://localhost:5432/phd"
    username: "phd"
    password: "phd"
  data:
    cassandra:
      session-name: "Data Cluster"
      keyspace-name: phd
      port: 9042
      contact-points: localhost
      local-datacenter: datacenter1


vvdump:
  named-pipe-path: "/tmp/vvdump"
  sql:
    postgres:
      insert-variable-value-trace-query: "INSERT INTO variable_value_trace VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
      insert-fuzzed-process-info-query: "INSERT INTO fuzzed_process_info VALUES (?, ?, ?, ?, ?, ?, ?, current_timestamp)"
      delete-variable-value-traces-query: "DELETE FROM variable_value_trace WHERE pid = ?"
    cassandra:
      trace-table-fields:
        experiments:
          - experiment
        experiment_subjects:
          - experiment
          - subject
        experiment_subject_binaries:
          - experiment
          - subject
          - binary
        experiment_subject_binary_executions:
          - experiment
          - subject
          - binary
          - execution
        subject_files:
          - subject
          - filename
        subject_file_functions:
          - subject
          - filename
          - function_name
        subject_file_function_variables:
          - subject
          - filename
          - function_name
          - variable_type
          - variable_name
          - declared_line
        subject_file_function_variables_by_declaration_order:
          - subject
          - filename
          - function_name
          - declared_line
          - variable_type
          - variable_name
        processes:
          - experiment
          - subject
          - binary
          - execution
          - pid
          - exit_status
          - input_size
        process_variable_value_traces:
          - id
          - experiment
          - subject
          - binary
          - execution
          - pid
          - exit_status
          - input_size
          - filename
          - function_name
          - declared_line
          - variable_type
          - variable_name
          - timestamp
          - modified_line
          - variable_value

logging:
  file:
    name: /tmp/vvdproc.log
  level:
    root: INFO
