FROM alpine:latest
ARG UNAME=vivin
ARG UID=1000
RUN apk update && apk add sudo bash curl libc-dev libpcap gcc make perl perl-dev perl-app-cpanminus
RUN adduser -h /home/vivin -u $UID -s /bin/bash --disabled-password $UNAME \
    && mkdir -p /etc/sudoers.d \
    && echo "$UNAME ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$UNAME \
    && chmod 0440 /etc/sudoers.d/$UNAME \
    && cpanm install inc::latest inc::Module::Install Redis YAML::XS Log::Simple::Color List::Util Cpanel::JSON::XS
COPY resources/docker/container_bashrc /home/vivin/.bashrc
COPY resources/binaries /home/vivin/Projects/phd/resources/binaries
COPY tools/FuzzFactory /home/vivin/Projects/phd/tools/FuzzFactory
COPY scripts /home/vivin/Projects/phd/scripts
COPY ["resources/fuzz_config.yml", "/home/vivin/Projects/phd/resources/"]
RUN chown -R $UNAME:$UNAME /home/vivin
USER $UNAME
