---
__global__:
  num_consumers: 300
  hours_per_iteration: 2
jsoncpp:
  fuzz_time: 300
  num_iterations: 3
  binary_name: readjson
  argument: "@@"
libtpms:
  fuzz_time: 300
  num_iterations: 12
  binary_name: readtpmc
  argument: "@@"
libpng:
  fuzz_time: 300
  num_iterations: 12
  binary_name: readjson
  argument: "< @@"
pcapplusplus:
  fuzz_time: 300
  num_iterations: 12
  binary_name: readpcap
  argument: "@@"
dmg2img:
  fuzz_time: 300
  num_iterations: 12
  binary_name: dmg2img
  argument: "@@"
readelf:
  fuzz_time: 300
  num_iterations: 12
  binary_name: readelf
  argument: "-a @@"
smbc:
  exec_or_run_matching:
    ^l0-:
      binary_arguments: 0
    ^l10-:
      binary_arguments: 10
    ^l11-:
      binary_arguments: 11
    ^l12-:
      binary_arguments: 12
    ^l13-:
      binary_arguments: 13
    ^l14-:
      binary_arguments: 14
    ^l16-:
      binary_arguments: 16
    ^l17-:
      binary_arguments: 17
    ^l18-:
      binary_arguments: 18
    ^l19-:
      binary_arguments: 19
    ^l2-:
      binary_arguments: 2
    ^l20-:
      binary_arguments: 20
    ^l21-:
      binary_arguments: 21
    ^l22-:
      binary_arguments: 22
    ^l23-:
      binary_arguments: 23
    ^l24-:
      binary_arguments: 24
    ^l25-:
      binary_arguments: 25
    ^l26-:
      binary_arguments: 26
    ^l27-:
      binary_arguments: 27
    ^l29-:
      binary_arguments: 29
    ^l3-:
      binary_arguments: 3
    ^l30-:
      binary_arguments: 30
    ^l31-:
      binary_arguments: 31
    ^l32-:
      binary_arguments: 32
    ^l33-:
      binary_arguments: 33
    ^l34-:
      binary_arguments: 34
    ^l35-:
      binary_arguments: 35
    ^l4-:
      binary_arguments: 4
    ^l5-:
      binary_arguments: 5
    ^l7-:
      binary_arguments: 7
    ^l8-:
      binary_arguments: 8
    ^l9-:
      binary_arguments: 9
