apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 1
  serviceName: redis-service
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: "Always"
          args:
            - "redis-server"
            - "--save"
            - "60"
            - "1"
            - "--loglevel"
            - "warning"
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: "/data"
              name: redis-pvc
          resources:
            limits:
              memory: 32Gi
              cpu: 4000m
            requests:
              memory: 2Gi
              cpu: 4000m
        - name: redis-backup
          command:
            - "/bin/bash"
            - "-c"
            - "/home/vivin/Projects/phd/scripts/backup_redis.pl"
          image: vivin/sandpuppy-analysis
          imagePullPolicy: Always
          stdin: true
          tty: true
          volumeMounts:
            - name: private-nfs
              mountPath: "/private-nfs"
            - name: redis-pvc
              mountPath: "/redis"
          resources:
            limits:
              cpu: 4000m
              memory: 32Gi
            requests:
              cpu: 4000m
              memory: 2Gi
          securityContext:
            privileged: true
      volumes:
        - name: private-nfs
          nfs:
            server: vivin.is-a-geek.net
            path: /media/2tb/phd-workspace/nfs
        - name: redis-pvc
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: NodePort
  ports:
   - port: 6379
     targetPort: 6379
     nodePort: 31111
     protocol: TCP
  selector:
    app: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  storageClassName: "openebs-hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi   # CHANGEME - the total disk space you will be able to use
