apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 1
  serviceName: redis-service
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: "Always"
          args:
            - "redis-server"
            - "--save"
            - "60"
            - "1"
            - "--loglevel"
            - "warning"
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: "/data"
              name: redis-pvc
          resources:
            requests:
              memory: '2Gi'
              cpu: '4000m'
            limits:
              memory: '4Gi'
              cpu: '4000m'
      volumes:
        - name: redis-pvc
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: NodePort
  ports:
   - port: 6379
     targetPort: 6379
     nodePort: 31111
     protocol: TCP
  selector:
    app: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  storageClassName: "openebs-hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi   # CHANGEME - the total disk space you will be able to use
