#!/bin/bash

INPUT_FILES_DIR=/mnt/kube-nfs/vivin/smartdsf/maze/results/sandpuppy-sync/$1/queue
CMD="cat $INPUT_FILES_DIR/% | workspace/smartdsf/maze/binaries/sandpuppy-vvhash-maze.c\:main\:player_col\:53\,player_row\:52/maze \"%\" | grep . > scratch/hashes/%.hash; sleep 1"

FILE_REGEX=$2
if [ -z "$FILE_REGEX" ]; then
    FILE_REGEX=".*id:.*"
fi

find $INPUT_FILES_DIR -maxdepth 1 -type f -regextype posix-extended -regex "$FILE_REGEX" | sort | sed -e 's,^.*queue/,,' | xargs -I % sh -c "$CMD"
