#!/bin/bash
EXP=$1
SUB=$2
BIN=$3
OUTPUT_PATTERN=$4

SYNC_DIR="/mnt/vivin-nfs/vivin/$EXP/$SUB/results/sandpuppy-sync"
BIN_DIR="/home/vivin/Projects/phd/workspace/$EXP/$SUB/binaries"
if [ ! -d "$BIN_DIR/sandpuppy-main" ]; then
    BINARY="$BIN_DIR/sandpuppy-main-asan/$BIN"
else
    BINARY="$BIN_DIR/sandpuppy-main/$BIN"
fi

declare -a solutions=()
while IFS= read -r -d '' dir
do
  # shellcheck disable=SC2001
  dirname=$(echo "$dir" | sed -e 's,^.*//,,')
  while IFS= read -r -d '' input
  do
    # shellcheck disable=SC2001
    filename=$(echo "$input" | sed -e 's,^.*/,,')
    echo "$dirname/$filename"
    echo ""
    ls -l "$input"
    $BINARY < "$input" | tee /tmp/out
    echo "================================================================="
    echo ""

    if [[ -n "$OUTPUT_PATTERN" ]]; then
      found=$(grep "$OUTPUT_PATTERN" /tmp/out)

      if [[ -n "$found" ]]; then
        solutions+=("$dirname/$filename (full path: $input)")
      fi
    fi
  done < <(find "$dir/queue" -maxdepth 1 -type f -name "id:*" -print0)
done < <(find "$SYNC_DIR" -mindepth 1 -maxdepth 1 -type d -print0)


if [[ "${#solutions[@]}" -gt 0 ]]; then
  echo "The following inputs generate outputs that match \"$OUTPUT_PATTERN\":"
  echo ""
  for solution in "${solutions[@]}"; do
    echo "  $solution"
  done
fi
