#!/bin/bash
EXP=$1
SUB=$2
RUN=$3
BIN=$4
SYNC_DIR="/mnt/vivin-nfs/vivin/$EXP/$SUB/results/$RUN/sandpuppy-sync"
BIN_DIR="/home/vivin/Projects/phd/workspace/$EXP/$SUB/binaries"
if [ ! -d "$BIN_DIR/sandpuppy-main" ]; then
    BINARY="$BIN_DIR/sandpuppy-main-asan/$BIN"
else
    BINARY="$BIN_DIR/sandpuppy-main/$BIN"
fi

for dir in `find $SYNC_DIR -mindepth 1 -maxdepth 1 -type d | sed -e 's,^.*/,,'`; do
  RESULT_DIR=$SYNC_DIR/$dir
  for crash in `find $RESULT_DIR/crashes -type f -name "id:*"`; do
    echo $crash
    echo ""
    #env ASAN_OPTIONS="abort_on_error=1:detect_leaks=0:symbolize=1:exitcode=86:allocator_may_return_null=1" $BINARY < $crash
    env ASAN_OPTIONS="abort_on_error=1:detect_leaks=0:symbolize=1:exitcode=86:allocator_may_return_null=1" $BINARY < $crash
    echo "================================================================="
    echo ""
  done
done
